apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: payment-ms
  name: payment-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment-ms
  template:
    metadata:
      labels:
        run: payment-ms
    spec:
      containers:
      - image: gcr.io/vaulted-channel-252309/payment-ms:latest
        name: payment-ms
        ports:
        - containerPort: 8080