apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rms-ms
  name: rms-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rms-ms
  template:
    metadata:
      labels:
        run: rms-ms
    spec:
      containers:
      - image: gcr.io/vaulted-channel-252309/rms-ms:latest
        name: rms-ms
        ports:
        - containerPort: 8080